/**
 * All known Playbook component names in PascalCase.
 * The processor's normalizeName() handles Figma alternate spellings
 * (spaces, underscores, "pb_" prefix) before checking this set.
 */

/** PascalCase Playbook component names. */
const SPEC_NAMES = [
  "AdvancedTable",
  "Avatar",
  "Background",
  "Badge",
  "BarGraph",
  "Body",
  "BreadCrumbs",
  "Button",
  "ButtonToolbar",
  "Caption",
  "Card",
  "Checkbox",
  "CircleChart",
  "CircleIconButton",
  "Collapsible",
  "Contact",
  "CopyButton",
  "Currency",
  "Dashboard",
  "DashboardValue",
  "Date",
  "DatePicker",
  "DateRangeInline",
  "DateRangeStacked",
  "DateStacked",
  "DateTime",
  "DateTimeStacked",
  "DateYearStacked",
  "Detail",
  "Dialog",
  "DistributionBar",
  "Draggable",
  "Drawer",
  "Dropdown",
  "EmptyState",
  "FileUpload",
  "Filter",
  "FixedConfirmationToast",
  "Flex",
  "FlexItem",
  "Form",
  "FormGroup",
  "FormPill",
  "Gauge",
  "Hashtag",
  "Highlight",
  "HomeAddressStreet",
  "Icon",
  "IconButton",
  "IconCircle",
  "IconStatValue",
  "IconValue",
  "Image",
  "LabelPill",
  "LabelValue",
  "Layout",
  "Legend",
  "Lightbox",
  "LineGraph",
  "Link",
  "List",
  "LoadingInline",
  "Map",
  "Message",
  "MultiLevelSelect",
  "MultipleUsers",
  "MultipleUsersStacked",
  "Nav",
  "NavItem",
  "OnlineStatus",
  "Overlay",
  "Pagination",
  "Passphrase",
  "Person",
  "PersonContact",
  "PhoneNumberInput",
  "Pill",
  "Popover",
  "ProgressPills",
  "ProgressSimple",
  "ProgressStep",
  "Radio",
  "RichTextEditor",
  "SectionSeparator",
  "Select",
  "SelectableCard",
  "SelectableCardIcon",
  "SelectableIcon",
  "SelectableList",
  "SkeletonLoading",
  "Source",
  "StarRating",
  "StatChange",
  "StatValue",
  "Table",
  "TextInput",
  "Textarea",
  "Time",
  "TimeRangeInline",
  "TimeStacked",
  "Timeline",
  "Timestamp",
  "Title",
  "TitleCount",
  "TitleDetail",
  "Toggle",
  "Tooltip",
  "Typeahead",
  "User",
  "UserBadge",
  "WeekdayStacked",
] as const

/**
 * Set of recognized Playbook component names in PascalCase.
 * The processor's normalizeName() handles Figma alternate spellings
 * (spaces, underscores, "pb_" prefix) before checking this set.
 */
export const PLAYBOOK_NAMES: ReadonlySet<string> = new Set(SPEC_NAMES)
